export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_ID = 'SET_USER_ID';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';

export const SET_DOCUMENTS = 'SET_DOCUMENTS';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const DOCUMENT_FETCHED = 'DOCUMENT_FETCHED';
export const DOCUMENT_UPDATED = 'DOCUMENT_UPDATED';
export const DOCUMENT_DELETED = 'DOCUMENT_DELETED';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';

export const SET_ROLE_ID = 'SET_ROLE_ID';
export const SET_USERS = 'SET_USERS';
export const USERS_FETCHED = 'USERS_FETCHED';
export const USER_DELETED = 'USER_DELETED';

export const PAGINATED_DOCUMENTS = 'PAGINATED_DOCUMENTS';
export const PAGINATED_USERS = 'PAGINATED_USERS';
